name: Update Velog Posts

on:
  push:
    branches:
      - main
  schedule:
    # í•œêµ­ ì‹œê°„ ê¸°ì¤€ ë§¤ì¼ ì˜¤ì „ 9ì‹œì— ì‹¤í–‰ (UTC 0ì‹œ)
    - cron: '0 0 * * *'
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ì„ ìœ„í•œ íŠ¸ë¦¬ê±° ì¶”ê°€

jobs:
  update_blog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install feedparser

    - name: Run script to update blog posts
      run: python scripts/update_blog.py

    - name: Push changes
      run: |
        git config --global user.name 'mygithub05253'
        git config --global user.email 'kik328288@gmail.com'
        git add .
        # ë³€ê²½ ì‚¬í•­ì´ ìˆì„ ë•Œë§Œ ì»¤ë°‹í•˜ë„ë¡ ìˆ˜ì •
        if ! git diff --staged --quiet; then
          git commit -m "ğŸ“š Velog posts updated by GitHub Actions"
          git push https://${{ secrets.GH_PAT }}@github.com/mygithub05253/velog-backup.git
        else
          echo "No changes to commit"
        fi
